attempt to make a string validator filler
phramework/validate-filler pull request #15
Opened 2017-06-27 14:33 UTC by VManolas

2017-06-28 09:44 UTC, nohponex requested changes
- [ ] Have 100% coverage

2017-06-28 09:44 UTC, nohponex commented on tests/src/StringValidatorFillerTest.php
> +        $returnedString = (new StringValidatorFiller())
Note that coveralls reported, (see PR comments)
> Coverage decreased (-1.6%) to 98.361%

it's better to use
```
(new Filler())
   ->fill($validator)
```

instead of directly using the StringValidatorFiller()

So will cover the Filler class switch case there
```

2017-06-28 17:16 UTC, VManolas commented on tests/src/StringValidatorFillerTest.php
> +        $returnedString = (new StringValidatorFiller())
I have updated this. But because I used `git commit --amend`, github cannot recognize the previous commit.

2017-06-30 09:18 UTC, nohponex commented on src/Filler.php
> +             * attempt to make a string validator filler
this comment is no longer needed

2017-07-02 18:17 UTC, nohponex requested changes

2017-07-02 18:17 UTC, nohponex commented on src/StringValidatorFiller.php
> +        $randomString = str_repeat('a', $length);
we might experiment with faker library now
or `\Phramework\Models\Util::readableRandomString`

as a better approach to repeating `a`

2017-07-04 06:28 UTC, VManolas commented
It lookes like the coverage has decreased. How could I fix this?

2017-07-04 07:34 UTC, nohponex commented
@VManolas 
> Error: Call to undefined function Phramework\ValidateFiller\readableRandomString()

Although travis didn't reported failure

2017-07-04 09:32 UTC, nohponex approved these changes

2017-07-04 09:33 UTC, nohponex commented
- [ ] @VManolas add a CHANGELOG.md entry for version 0.6.0 and we are ready to go

2017-07-04 09:34 UTC, nohponex requested changes
@VManolas add a CHANGELOG.md entry for version 0.6.0 and we are ready to go

2017-07-04 09:46 UTC, nohponex approved these changes

2017-07-04 09:47 UTC, merged