Implement dateValidator and datetimeValidator fillers
phramework/validate-filler pull request #17
Opened 2019-10-24 10:22 UTC by alkallio

2019-10-24 10:38 UTC, alkallio commented
Should we drop testing in php 7.0, 7.1, nightly and add 7.2, 7.3?

2019-10-25 09:27 UTC, akalineskou commented
dont forget to push the changes

2019-10-29 12:01 UTC, nohponex requested changes
declare strict everywhere

2019-10-29 12:01 UTC, nohponex commented on src/DateValidatorFiller.php
> +
declare strict

2019-10-29 12:01 UTC, nohponex commented on tests/src/DateValidatorFillerTest.php
> +
declare strict everywhere

2019-10-29 12:09 UTC, alkallio commented
Squash when merge.

2019-10-29 12:19 UTC, nohponex approved these changes

2019-10-29 12:19 UTC, merged